Create a shared utils folder for shared functions and add more details and logic to questionlist
Omega-outlet/FEC pull request #15
Opened 2023-08-12 23:54 UTC by ESC8504

Created a shared utils folder for shared functions, added sort by helpfulness function, and reformat date function.
Added more details to the Questionlist.jsx file and sorted questions in order of helpfulness

2023-08-13 02:01 UTC, tomki1 requested changes
It looks good! Maybe add at least one test to test sort by helpfulness function?

2023-08-13 18:15 UTC, ESC8504 commented
Forgot about the test, will do it!

2023-08-14 17:02 UTC, tomki1 approved these changes
Looks good!

2023-08-14 17:09 UTC, LLaxt approved these changes

2023-08-14 17:09 UTC, LLaxt commented on client/utils/reFormatDate.js
looks good! I wonder if there is an in-built way to format date?
I'd also change the filename to "reformatDate" just for consistency, but not important!

2023-08-14 17:19 UTC, merged